CREATE DATABASE IF NOT EXISTS cadastro
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE cadastro;

CREATE TABLE IF NOT EXISTS clientes(
	cpf CHAR(11) PRIMARY KEY,
	nome_completo VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS contato_cliente(
	id_contato INT PRIMARY KEY AUTO_INCREMENT,
    telefone CHAR(11) NOT NULL,
    email VARCHAR(100) NOT NULL,
    cpf_cliente CHAR(11) NOT NULL,
    CONSTRAINT fk_cpf_cliente FOREIGN KEY(cpf_cliente) REFERENCES clientes(cpf) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
